[package]
name = "ecs"
version = "0.1.0"
authors = ["scifi6546 <scifi6546@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.7.3"
nalgebra="0.21.1"
